### ISSUE TITLE
Input from one MQTT connection, output to another MQTT connection

### ISSUE THREAD

**Issue by janeski-zz** [keesschollaart81/CaseOnline.Azure.WebJobs.Extensions.Mqtt#10]
Hi, the library is great and it's something It really fits to my needs right now. I was just curious if it's possible to set one connection for input and another one for output? My use case is to subscribe to one and to publish filtered messages to another broker.

**Comment by keesschollaart81** [comment]
Yes. Use the ConnectionString property on the trigger & output attributes and point it to 2 different connectionstrings in your setttings. That should work!

**Comment by janeski-zz** [comment]
Great, I've checked the wiki page and managed to create the two connection strings I need. Thanks.
