### ISSUE TITLE
Message to one topic also triggers another function with different topic

### ISSUE THREAD

**Issue by ghost** [keesschollaart81/CaseOnline.Azure.WebJobs.Extensions.Mqtt#11]
Hi,

I have assigned two triggers for different topics to two functions as in the following code snippet:
```csharp
public static class TTNAzureDeviceManagement
{
    [FunctionName("OnDeviceCreate")]
    public static async Task OnDeviceCreate([MqttTrigger(typeof(TTNMqttConfigProvider), "ttn-mapper-jsi/devices/+/events/create")] IMqttMessage message, ILogger logger)
    {
        logger.LogInformation($"{DateTime.Now:g} Creation message from topic {message.Topic}");
        ....
    }

    [FunctionName("OnDeviceDelete")]
    public static async Task OnDeviceDelete([MqttTrigger(typeof(TTNMqttConfigProvider), "ttn-mapper-jsi/devices/+/events/delete")] IMqttMessage message, ILogger logger)
    {
        logger.LogInformation($"{DateTime.Now:g} Deletion message from topic {message.Topic}");
        ....
    }
}
```
When I now run these function on Azure and send a message to one of the topics (e.g. devices/+/events/create) both functions are executed as can be seen in the following log:
```
2019-03-10T12:36:11.741 [Information] Executing 'OnDeviceCreate' (Reason='Mqtt fired at 2019-03-10T12:36:11.7416672+00:00', Id=84a4a1e1-136d-4cd6-847d-4c79fc5311c6)
2019-03-10T12:36:11.743 [Information] 3/10/2019 12:36 PM Creation message from topic ttn-mapper-jsi/devices/test/events/delete
2019-03-10T12:36:11.788 [Information] 3/10/2019 12:36 PM Added device test to IoT Hub
2019-03-10T12:36:11.788 [Information] Executed 'OnDeviceCreate' (Succeeded, Id=84a4a1e1-136d-4cd6-847d-4c79fc5311c6)
```

Notice that the "OnDeviceCreate" function was executed while the topic which was triggered was "devices/test/events/**delete**". The "OnDeviceDelete" functions is executed as well but that's in another log.

Is this a bug or am I doing something wrong here?

Thanks in advance!

**Comment by ghost** [comment]
I've tested this again with the latest beta (1.2.0-beta.1248) but it still shows the same behaviour.

**Comment by keesschollaart81** [comment]
Correct, this was a bug. I was able to reproduce it (see unit test in linked commit ^) and fix it.

I'll push out v2.0 this weekend.

**Comment by Skydragonsz** [comment]
I still have this issue, it still triggers the wrong function.
I'm on version 2.0.2
