### ISSUE TITLE
Access to Application Settings in MQTT Topic definition

### ISSUE THREAD

**Issue by ghost** [keesschollaart81/CaseOnline.Azure.WebJobs.Extensions.Mqtt#12]
Hi,

according to [this document on Azure Functions Binding Syntax](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-expressions---app-settings) it should be possible to access the Application Settings of a Functions App by using the `%AppSetting%` syntax in the definition of a binding. Unfortunately this doesn't seem to work in my code which is implemented as follows:
```csharp
[FunctionName("OnDeviceCreate")]
public static async Task OnDeviceCreate([MqttTrigger(typeof(TTNMqttConfigProvider), "%TTNAppID%/devices/+/events/create")] IMqttMessage message, ILogger logger)
{
    logger.LogInformation($"{DateTime.Now:g} Creation message for topic {message.Topic}");
    ....
```

Is there another way to access Application Settings from an MqttTrigger Binding Definition?

Thanks in advance!

**Comment by keesschollaart81** [comment]
I've just pushed a beta over v1.2.0 to [MyGet](https://www.myget.org/feed/caseonline/package/nuget/CaseOnline.Azure.WebJobs.Extensions.Mqtt). If you could test that, that would be great. Otherwise I'll release it in 2 days.

**Comment by ghost** [comment]
Hi,

your solution works like a charm and looks way more elegant than mine by the way. So I'm absolutetly fine with prefering your solution over mine!
