### ISSUE TITLE
Maybe username/password configuration does not work?

### ISSUE THREAD

**Issue by morixhub** [keesschollaart81/CaseOnline.Azure.WebJobs.Extensions.Mqtt#161]
Hello. I am trying to write an Azure Function which subscribes to some topics on a MQTT broker, but I am not able to complete the authentication...

I mean: I am using a connection string like:

`"MqttConnection": "Server=my.server.com;Username=12345;Password=mypassword"`

but if I attach the debugger to the MQTT broker (based on MQTTnet) is see that both username and password in the MqttServer's authentication validator are *always* null (and so the MQTT broker validator implementation refuses the connection).

Am I forgetting something?

If I modify the broker implementation for accepting any username/password (even null) then everything else works perfectly fine... so I am close to the success, but still missing the authentication part... can anybody help? Thanks.

**Comment by justoke** [comment]
This format works for me
"MqttConnection": "Server=somemqtt.azurecontainer.io;Tls=false;Username=user1;Password=usepwd;"

**Comment by justoke** [comment]
A code sample

```
 /// <summary>
        /// Mqtt triggered by messages received on specific topic.
        /// </summary>
        /// <param name="message">Mqtt message received that triggered the function.</param>
        /// <param name="outMessage">Mqtt reponse output message.</param>
        /// <param name="logger">Logger used to log activity.</param>
        [FunctionName("OnMqtt")]
        public void OnMqttFunction(
        [MqttTrigger("system/device/+/state")] IMqttMessage message,
        [Mqtt] out IMqttMessage outMessage,
        ILogger logger)
        {
            var body = message?.GetMessage();
            var bodyString = Encoding.UTF8.GetString(body);
            logger?.LogInformation($"{DateTime.Now:g} Message for topic {message?.Topic}: {bodyString}");
            outMessage = new MqttMessage(this.configuration.TopicBroadcastAllOut, body, MqttQualityOfServiceLevel.AtLeastOnce, true);
        }
```

**Comment by morixhub** [comment]
Thank you justoke: probably there was something wrong in the deployment of my function to Azure... now I rebuilt everything and re-deployed to Azure from scratch and everything works fine!

Anyway thank you for your time and kind support! Awesome.
